name: Update Locale

# This action runs:
# - When this file changes
# - When changes on documentation (doc)
# - When is triggered manually

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/locale.yml'
      - 'doc/**'
      - 'locale/**'
      - 'CMakeLists.txt'

    branches-ignore:
      - 'gh-pages'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
    release: Release
    os: ubuntu-latest
    vroom: 1.12.0

jobs:
  update-locale:
    name: Update Locale
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get postgres version
        run: |
          sudo service postgresql start
          PGVER=$(psql --version | grep -Po '(?<=psql \(PostgreSQL\) )[^;]+(?=\.\d+ \()')
          echo "PGVER=${PGVER}" >> $GITHUB_ENV
          echo "PGPORT=5432" >> $GITHUB_ENV

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update

          # Basic dependencies
          sudo apt-get install -y \
            postgresql-${PGVER} \
            postgresql-server-dev-${PGVER}

          # vroom dependencies
          sudo apt-get install libssl-dev libasio-dev libglpk-dev

          # documentation dependencies
          sudo apt-get install -y \
            graphviz \
            python3-sphinx \
            python3-sphinx-bootstrap-theme \
            sphinx-intl

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ env.release }} -DSPHINX_LOCALE=ON \
                -DDOC_ONLY=ON ..

      - name: Build the locale files
        run: |
          cd build
          make locale

      - name: Extract branch name and commit hash
        run: |
          branch=${GITHUB_REF#refs/heads/}
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "GIT_HASH=$git_hash" >> $GITHUB_ENV

      - name: Initialize mandatory git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update locale
        run: |
          bash .github/scripts/update_locale.sh
          # Add the files, commit and push
          git diff --staged --quiet || git commit -m "Update locale: commit for hash ${{ env.GIT_HASH }}"
          git restore .  # Remove the unstaged changes before rebasing
          git push
